### ISSUE TITLE
两点建议

### ISSUE THREAD

**Issue by JehuMa** [clan4456/CSTK_Button_Icon#2]
1.有时候我只是想统一换个文本或者统一换个logo，如果打开统一修改全部状态就会把我不想要修改的状态也修改了，只能选择单独修改状态然后一个个改图标。
2.出个保存功能，把我认为做的比较好的按钮保存到“clan studio toolkits”下或您认为合适的位置。

**Comment by clan4456** [comment]
已收到，将在下个版本更新的时候考虑加入。

感谢反馈和提供建议
